### ISSUE TITLE
 Add Bad Apple

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz-wasm-examples#9]
https://github.com/hsfzxjy/Bad-Apple-Font

**Comment by alerque** [comment]
This one is cool, but a little different than other font links. The others are just the font with some hints about how to go build your own Harfbuzz. This one has the Harfbuzz download, build, and run all scripted. Scripting it is fine, but the way it is all done is more dangerous to end users just running things than the entire WASM shaper is in the first place. I'm not saying don't include it, but with the already weak understanding of the current experimental disabled-by-default state, that repository isn't going to do the WASM idea any favors on the security front. I suggest a disclaimer about the the safety of auto download/build/run tooling if it is linked.

**Comment by behdad** [comment]
You're also right that it doesn't actually use the shaping facility really. Nevrermind.
